FROM rocker/shiny:latest
RUN install2.r  --skipinstalled --error \
    rsconnect shiny shinyWidgets \
    dygraphs ggplot2 plotly xts viridis \
    dplyr bslib here stringr lubridate  \
    intensegRid logger \
    && rm -rf /tmp/downloaded_packages

WORKDIR /opt/app
