



ui <- fluidPage(
  theme = my_theme,
  # includeCSS("styles.css"),
  div(
    id = "header",
    titlePanel("How much consumed energy is renewable?"),
    div(
      style = "display: inline-block; width: 250px;",
      span("View as heatmap", style = "font-size: large;"),
      materialSwitch(inputId = "heatmap", label = NULL, status = "primary")
    ),
    div(
      id = 'region-selector',
      style = "display: grid; justify-items: center;",
      span("Search for a region", style = "font-size: small;"),
      selectizeInput(
        'region',
        label = NULL,
        choices = c("", unique_regions),
        multiple = FALSE
      )
    )
  ),
  uiOutput("carbon_plot", height = 850),
  div(
    id = "data_info",
    icon("database"),
    "Data sourced from",
    a(href = "https://carbonintensity.org.uk/", "Carbon Intensity API from National Grid"),
    "generated by taking average carbin intensity from weather stations over the years 1982-2010."
  ),
  br(),
  div(
    id = "source_link",
    a(href = "https://github.com/KKulma/carbon-intensity-app/", "View source code on github", icon("github"))
  )
)
