ui <- fluidPage(
  theme = my_theme,
  div(
    id = "header",
    titlePanel(h1("How much UK electricity comes from low-carbon sources?", align = "center")),
    div(
      style = "display: inline-block; width: 250px;",
      span("View as heatmap", style = "font-size: large;"),
      materialSwitch(
        inputId = "heatmap",
        label = NULL,
        status = "primary"
      )
    ),
    div(
      id = 'region-selector',
      style = "display: grid; justify-items: center;",
      span("Search for a region", style = "font-size: large;"),
      selectizeInput(
        'region',
        label = NULL,
        choices = c("", unique_regions),
        selected = "London",
        multiple = FALSE
      )
    )
  ),
  uiOutput("carbon_plot", height = 850),
  br(),
  div(
    id = "data_info",
    icon("database"),
    "Data sourced from",
    a(href = "https://carbonintensity.org.uk/", "Carbon Intensity API from National Grid"),
    "generated by taking average daily carbon intensity based on 1/2-hourly intervals."
  ),
  div(
    id = "source_link",
    a(icon("github"), href = "https://github.com/KKulma/carbon-intensity-app/", "View source code on github")
  )
)
