
ui <- fluidPage(
  theme = my_theme,
  # includeCSS("styles.css"),
  div(id = "header",
      titlePanel("How much consumed energy is renewable?"),
      labeled_input('region-selector', "Search for a region",
                    selectizeInput('region', label = NULL,
                                   choices = c("", unique_regions),
                                   multiple = FALSE)),
      labeled_input("prev_region_btn", "Return to previous region",
                    actionButton('prev_region', textOutput('prev_region_label')))),
  plotOutput("carbon_plot", height = 850),
  div(id = "data_info",
      icon("database"), "Data sourced from",
      a(href = "https://carbonintensity.org.uk/", "Carbon Intensity API from National Grid"),
      "generated by taking average carbin intensity from weather stations over the years 1982-2010."),
  div(id = "source_link", a(href = "https://github.com/KKulma/carbon-intensity-app/", "View source code on github", icon("github")))
)

