name: deploy
on:
  push:
    branches:
      - main
jobs:
  re-deploy:
    runs-on: ubuntu-latest
    container:
      image: kasiatemp/carbon-intensity-shiny:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Deploy app
        env:
          SHINY_ACC_NAME: ${{secrets.SHINY_ACC_NAME}}
          TOKEN: ${{secrets.TOKEN}}
          SECRET: ${{secrets.SECRET}}
        run: |
          bash ./deploy/deploy.sh
