name: append daily CI data

on: 
 schedule:  
   - cron:  '0 6 * * *'
jobs:
  run_container:
    runs-on: ubuntu-latest
    container:
      image: kasiatemp/ng-update:daily
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Update data
        run: |
          bash ./data-raw/update-data.sh
      - name: Commit files
        run: |
          git config --local user.name 'Kasia'
          git config --local user.email 'katarzyna.kulma@gmail.com'
          git commit -m "Auto update of the daily data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
