name: append daily CI data
name: update carbon intensity data

on:
  schedule:  
    - cron:  '0 6 * * *'
jobs:
  run_container:
    runs-on: ubuntu-latest
    container:
      image: kasiatemp/ng-update:daily
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Update data
        run: |
          source("data-raw/update-data.R")
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.email "katarzyna.kulma@gmail.com"
          git config --local user.name "Kasia"
          git add --all
          git commit -am "update daily data"
          git push 

